name: iOS CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: Run Xcode Tests
    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Install dependencies
        run: |
          brew install cocoapods
          pod install || true

      - name: Build and test
        run: |
          xcodebuild -project RickAndMorty.xcodeproj \
                     -scheme TestCICD \
                     -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.0' \
                     clean test